language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py35
    - TOXENV=py36
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
script:
  - tox
